//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmergencyX_Client.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmergencyX_Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Emergency X ähnelt.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Emergency Explorer ähnelt.
        /// </summary>
        public static string appTitle {
            get {
                return ResourceManager.GetString("appTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Change load order  ähnelt.
        /// </summary>
        public static string c {
            get {
                return ResourceManager.GetString("c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Changes successfully saved. ähnelt.
        /// </summary>
        public static string changesSuccessfullSaved {
            get {
                return ResourceManager.GetString("changesSuccessfullSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Emergency X has to be restarted because the Emergency installation path has cahanged. ähnelt.
        /// </summary>
        public static string clientRestartNeeded {
            get {
                return ResourceManager.GetString("clientRestartNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application restart ähnelt.
        /// </summary>
        public static string clientRestartNeededTitle {
            get {
                return ResourceManager.GetString("clientRestartNeededTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activ? ähnelt.
        /// </summary>
        public static string columnHeaderModActiv {
            get {
                return ResourceManager.GetString("columnHeaderModActiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modification ähnelt.
        /// </summary>
        public static string columnHeaderModName {
            get {
                return ResourceManager.GetString("columnHeaderModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load order ähnelt.
        /// </summary>
        public static string columnHeaderModOrderingIndex {
            get {
                return ResourceManager.GetString("columnHeaderModOrderingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Enable or disable marked modification ähnelt.
        /// </summary>
        public static string e {
            get {
                return ResourceManager.GetString("e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Emergency installation path ähnelt.
        /// </summary>
        public static string emergencyInstallationPath {
            get {
                return ResourceManager.GetString("emergencyInstallationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Emergency is installed ähnelt.
        /// </summary>
        public static string emergencyIsInstalled {
            get {
                return ResourceManager.GetString("emergencyIsInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Emergency is not installed ähnelt.
        /// </summary>
        public static string emergencyIsNotInstalled {
            get {
                return ResourceManager.GetString("emergencyIsNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while reading the settings. ähnelt.
        /// </summary>
        public static string errErrorOnSettingsRead {
            get {
                return ResourceManager.GetString("errErrorOnSettingsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while saving the settings. ähnelt.
        /// </summary>
        public static string errErrorOnSettingsSave {
            get {
                return ResourceManager.GetString("errErrorOnSettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login failed! ähnelt.
        /// </summary>
        public static string loginFailed {
            get {
                return ResourceManager.GetString("loginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activ:  ähnelt.
        /// </summary>
        public static string prefixEnabled {
            get {
                return ResourceManager.GetString("prefixEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modification:  ähnelt.
        /// </summary>
        public static string prefixModificationName {
            get {
                return ResourceManager.GetString("prefixModificationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordering Index:   ähnelt.
        /// </summary>
        public static string prefixOrderingIndex {
            get {
                return ResourceManager.GetString("prefixOrderingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Run Emergency ähnelt.
        /// </summary>
        public static string runEmergency {
            get {
                return ResourceManager.GetString("runEmergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Settings ähnelt.
        /// </summary>
        public static string settingsButtonContent {
            get {
                return ResourceManager.GetString("settingsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modify settings ähnelt.
        /// </summary>
        public static string settingsButtonToolTip {
            get {
                return ResourceManager.GetString("settingsButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string settingsTitle {
            get {
                return ResourceManager.GetString("settingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brotil (advanced) ähnelt.
        /// </summary>
        public static string settingUseBrotli {
            get {
                return ResourceManager.GetString("settingUseBrotli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zip (default) ähnelt.
        /// </summary>
        public static string settingUseZip {
            get {
                return ResourceManager.GetString("settingUseZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Which compression algorithm should be used? ähnelt.
        /// </summary>
        public static string settingZipOrBrotilDescription {
            get {
                return ResourceManager.GetString("settingZipOrBrotilDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sign in ähnelt.
        /// </summary>
        public static string signInButtonContent {
            get {
                return ResourceManager.GetString("signInButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Perform login ähnelt.
        /// </summary>
        public static string signInButtonToolTip {
            get {
                return ResourceManager.GetString("signInButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sign out ähnelt.
        /// </summary>
        public static string signOutButtonContent {
            get {
                return ResourceManager.GetString("signOutButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Perform logout ähnelt.
        /// </summary>
        public static string signOutButtonToolTip {
            get {
                return ResourceManager.GetString("signOutButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login successfull! ähnelt.
        /// </summary>
        public static string successFullLoggedIn {
            get {
                return ResourceManager.GetString("successFullLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
